[programs.localnet]
luxeshare = "11111111111111111111111111111111"

[programs.devnet]
luxeshare = "11111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "pnpm -C ts test"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/luxeshare"]